version: '3.1'

services:
  worker:
    image: bennythink/ytdlbot
    env_file:
      - env/ytdl.env
    restart: always
    command: [ "/usr/local/bin/supervisord", "-c" ,"/ytdlbot/conf/supervisor_worker.conf" ]
#    network_mode: "host"
#    deploy:
#      resources:
#        limits:
#          cpus: '0.3'
#          memory: 1500M
